### ISSUE TITLE
trait NodeCategoryTrait问题

### ISSUE THREAD

**Issue by charlesyq** [vergil-lai/node-categoires#3]
再来个
`public function childrens()
    {
        return $this->where('node', 'like', $this->node.'%')->get();
    }`

这个忘了把自己去除掉吧，应该是
`public function childrens()
    {
        return $this->where('node', 'like', $this->node.'%')->->where('id', '!=', $this->id)->get();
    }`
吧

**Comment by vergil-lai** [comment]
感谢你提出的建议，下个版本将会修复。也欢迎你直接提交代码
